# Generated by Django 5.1.7 on 2025-06-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_ban_duration_userprofile_ban_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_interests',
            field=models.BooleanField(default=True, verbose_name='Show interests to other users'),
        ),
    ]
