# Generated by Django 5.2.1 on 2025-06-19 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='name',
        ),
    ]
