# Generated by Django 5.2.1 on 2025-06-19 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_remove_forum_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_text', models.TextField(max_length=256)),
                ('complaint_time', models.DateTimeField(auto_now_add=True)),
                ('complaint_type', models.CharField(choices=[('hate_speech', 'hate speech'), ('spam', 'spam'), ('offensive', 'offensive'), ('harassment', 'harassment'), ('other', 'other')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('reviewed', 'reviewed'), ('dismissed', 'dismissed')], default='pending', max_length=16)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_made', to=settings.AUTH_USER_MODEL)),
                ('comment_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forums.comment')),
                ('forum_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forums.forum')),
                ('topic_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forums.topic')),
                ('user_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
