# Generated by Django 5.2.1 on 2025-06-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forums", "0003_complaint"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum",
            name="name",
            field=models.CharField(default="Anonymous", max_length=50),
        ),
    ]
