# Generated by Django 5.2.1 on 2025-06-19 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_forum_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='name',
        ),
    ]
