# Generated by Django 5.2.1 on 2025-06-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_remove_forum_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='name',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
